version: "3"
services:
  traveloka-work:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo/travekola-app
    depends_on:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
